<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario de registro de usuarios</title>
</head>
<body>
    <h1>¡Vamos a crear tu nuevo usuario!</h1>
    <form action="index.php?c=user" method="post">
        <input type="file" name="avatar" placeholder="Selecciona tu foto" />
        <input type="text" name="email" name="email" placeholder="introduce tu email">
        <input type="text" name="username" placeholder="Nombre de usuario">
        <input type="password" name="password" placeholder="Introduce tu contraseña">
        <input type="submit" name="newUser" value="Crear usuario" />
</body>
</html>