<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

    <form action="index.php?c=user" method="post" >
        <input type="text" name="name" placeholder="NOMBRE DEL PRODUCTO">
        <input type="text" name="description" placeholder="DESCRIPCIÓN DEL PRODUCTO">
        <input type="text" name="image" placeholder="imagen del producto">
        <input type="number" name="price" placeholder="PRECIO DEL PRODUCTO EN €">
        <input type="number" name="stock" placeholder="CANTIDAD">

        <input type="submit" name="create" value="CREAR PRODUCTO">
    </form>


</body>
</html>