<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Carrito</title>
</head>
<body>
    <h1>Carrito de Compras</h1>
    
    <?php
        foreach ($productCarrito as $product){
            echo '<li>'.$product->getName().'</li>'.
			'<form action="index.php?v=carritoView" method="post">
				<input type="hidden" name="id" value="'.$product->getId().'"/>
				<input type="hidden" name="precio" value="'.$product->getPrice().'"/>
				<input type="submit" name="carrito" value="Añadir al carrito"/>
			</form>
		';
        }


        ///// EL CARRITO VIEW NO ESTÁ TERMINADO
        
    ?>
    
</body>
</html>