<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

    <form action="index.php?c=user" method="post" >
        <input type="text" name="user" placeholder="Usuario">
        <input type="password" name="password" placeholder="contraseña">
        <input type="submit" name="login" value="Login">
    </form>


</body>
</html>