<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modificación usuarios</title>
</head>
<body>
    <h1> Página para hacer usuarios administradores </h1>
    
    <form action="index.php?y=modificar" method="post" >
        <input type="text" name="username" placeholder="Nombre de Usuario">
        <input type="submit" name="makeAdmin" value="Hacer Administrador">
    </form>
</body>
</html>