<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear nueva canción</title>
</head>

<body>
    <h1>Crear nueva canción</h1>
    <form action="index.php?n=create" method="post">
        <input type="text" name="title" placeholder="Título de la canción">
        <input type="text" name="author" placeholder="Nombre del autor">
        <input type="text" name="duration" placeholder="60">
        <input type="submit" name="añadirCancion" value="Crear lista">
    </form>
    <form action="index.php?a=atras">
        <input type="submit" value="Atrás">
    </form>
</body>

</html>