<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear usuario</title>
</head>
<body>
    <form method="post" action="index.php?c=user">
        <input type="text" name="username" placeholder="Nombre del usuario">
        <input type="password" name="password" placeholder="Contraseña">
        <input type="submit" name="newUser" value="Crear Usuario">
    </form>
    <form action="index.php?a=atras">
        <input type="submit" value="Atrás">
    </form>
</body>
</html>