<?php
// Asegurándote de que las clases necesarias están incluidas
require_once(__DIR__ . '/../models/AddModel.php');
require_once(__DIR__ . '/../models/SongModel.php');
require_once(__DIR__ . '/../models/SongRepository.php');

echo '<h1>Detalles de la Lista de Reproducción</h1>';

if (!empty($songsInList)) {
    echo '<h2>Titulo de la lista:  '.$listTitle = ListRepository::getTitleOfListById($listId).'</h2>';
    echo '<ul>';
    foreach ($songsInList as $song) {
        // Obteniendo los detalles de la canción utilizando getIdSongs()
        $songDetails = SongRepository::getSongById($song->getIdSongs());
        $minSec = SongRepository::convertMinutesAndSeconds($songDetails->getDuration());
        echo '<li>' . htmlspecialchars($songDetails->getTitle()) . ' - ' . htmlspecialchars($songDetails->getAuthor()) .' - '.$minSec .'</li>';
    }
    echo '</ul>';
    
} else {
    echo '<p>No hay canciones en esta lista de reproducción.</p>';
}
echo '<form action="index.php?a=atras">
        <input type="submit" value="Atrás">
    </form>'
?>


