<!DOCTYPE html>
<html>
<head>
	<title>Mi lista de peliculas</title>
</head>
<body>
<h1>Mi lista de peliculas</h1>

<?php
	echo 'Bienvenido';

	echo '<form action="index.php" method="post">
		<input type= "submit" name="logout" value="Cerrar sesion" />
	</form>';

	echo '<form action="index.php?i='.$_SESSION['user']->getUsername().'" method="post">
	<input type="submit" name="info" value="Informacion usuario" /><br>';
?>

<form action="index.php" method="post">
	<input type="text" name="busca" placeholder="Titulo para la búsqueda">
	<input type="submit" value="Busca">
</form>

<ul>
<?php

foreach ($movies as $movie) {
	echo '<li>'.$movie->getTitle().' (Estrenado en '.$movie->getYear().')</li>';
	echo '<form action="index.php method="post">
	<input type="hidden" name= "id" value= "'.$movie->getId().'">
	<input type="submit" name="borrar" value="borrar">
	</form>';
	echo '<form action="index.php?p='.$movie->getTitle().'" method="post">
	<input type="submit" name="Favorita" value="❤️">
	</form>';
}

echo '<form action="index.php" method="post">
	<input type="text" name= "title" placeholder="Titulo" >
	<input type="number" name= "year" placeholder="Año de estreno" >
	<input type="text" name="poster" placeholder="Imagen">
	<input type="submit" name="add" value="Añadir">
	</form>';


?>
</ul>
</body>
</html>